# Generated by Django 5.1.1 on 2024-10-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakerdataapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fakerdata',
            name='hall_ticket',
            field=models.BigIntegerField(),
        ),
    ]
